version: "3.3"
services:
  web:
    container_name: butena_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALGORITHM=${ALGORITHM}
      - API_ENV=${API_ENV}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_TITLE=${API_TITLE}
      - API_VERSION=${API_VERSION}
      - BUCKET_NAME=${BUCKET_NAME}
      - BUCKET_ZONE=${BUCKET_ZONE}
      - DESCRIPTION=${DESCRIPTION}
      - DOC_URL=${DOC_URL}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - POSTGRES_DB=butena
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=butena
      - POSTGRES_PORT=5432
      - POSTGRES_USER=butena
      - REDOC_URL=${REDOC_URL}
      - SERVER_RELOAD=${SERVER_RELOAD}
      - TEMP_DIR=${TEMP_DIR}
      - WORKER_COUNT=${WORKER_COUNT}

    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=butena
      - POSTGRES_PASSWORD=butena
      - POSTGRES_DB=butena
volumes:
  postgres_data:
