version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SERVER_RELOAD: false
      POSTGRES_HOST: db
      JWT_SECRET_KEY: nothing_special
      JWT_REFRESH_SECRET_KEY: very_special
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=butena
      - POSTGRES_PASSWORD=butena
      - POSTGRES_DB=butena
volumes:
  postgres_data:
